version: '2'

networks:
  etcd-network:
    driver: bridge

services:
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://localhost:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - etcd-network

